CREATE TABLE `savedQuotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quoteName` varchar(200) NOT NULL,
	`company` enum('L&M','Peach') NOT NULL,
	`clientCompany` varchar(200),
	`clientContact` varchar(100),
	`clientAddress1` varchar(200),
	`clientAddress2` varchar(100),
	`clientCity` varchar(100),
	`clientState` varchar(2),
	`clientZip` varchar(10),
	`clientPhone` varchar(20),
	`clientEmail` varchar(320),
	`facilityId` varchar(50) NOT NULL,
	`monthlyPallets` int NOT NULL,
	`monthlyTurns` int NOT NULL,
	`sqFtPerPallet` int NOT NULL,
	`stackHeight` int NOT NULL,
	`fullyLoadedLaborRate` int NOT NULL,
	`inboundMinutes` int NOT NULL,
	`outboundMinutes` int NOT NULL,
	`storageMargin` int NOT NULL,
	`handlingInMargin` int NOT NULL,
	`handlingOutMargin` int NOT NULL,
	`pickType` enum('full','layer','case') NOT NULL,
	`monthlyOrders` int NOT NULL,
	`casesPerOrder` int NOT NULL,
	`labelsPerOrder` int NOT NULL,
	`casePickRate` int NOT NULL,
	`layerPickRate` int NOT NULL,
	`palletSupplyFee` int NOT NULL,
	`shrinkWrapFee` int NOT NULL,
	`labelingFee` int NOT NULL,
	`orderProcessingFee` int NOT NULL,
	`cancellationFee` int NOT NULL,
	`casePickMargin` int NOT NULL,
	`palletSupplyMargin` int NOT NULL,
	`shrinkWrapMargin` int NOT NULL,
	`labelingMargin` int NOT NULL,
	`orderProcessingMargin` int NOT NULL,
	`tier1Name` varchar(50),
	`tier1Length` varchar(50),
	`tier1Discount` int,
	`tier2Name` varchar(50),
	`tier2Length` varchar(50),
	`tier2Discount` int,
	`tier3Name` varchar(50),
	`tier3Length` varchar(50),
	`tier3Discount` int,
	`tier4Name` varchar(50),
	`tier4Length` varchar(50),
	`tier4Discount` int,
	`selectedDiscountTier` varchar(20),
	`storageRateOverride` int,
	`handlingInRateOverride` int,
	`handlingOutRateOverride` int,
	`quoteValidDays` int,
	`paymentTerms` varchar(100),
	`minimumCommitment` varchar(100),
	`customDisclosures` text,
	`createdBy` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `savedQuotes_id` PRIMARY KEY(`id`)
);
