CREATE TABLE `pipelineDeals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientName` varchar(200) NOT NULL,
	`clientContact` varchar(200),
	`clientEmail` varchar(320),
	`clientPhone` varchar(20),
	`dealName` varchar(300) NOT NULL,
	`serviceType` enum('warehousing','transportation','ecommerce','crossdock','rework','mixed') NOT NULL,
	`facility` varchar(100),
	`company` enum('L&M','Peach') NOT NULL DEFAULT 'L&M',
	`stage` enum('lead','proposal_sent','under_review','negotiating','signed','active','lost') NOT NULL DEFAULT 'lead',
	`estimatedMonthlyRevenue` int,
	`estimatedAnnualRevenue` int,
	`estimatedPallets` int,
	`estimatedLoads` int,
	`proposalDate` timestamp,
	`expectedCloseDate` timestamp,
	`actualCloseDate` timestamp,
	`savedQuoteId` int,
	`keyServices` text,
	`notes` text,
	`probability` int,
	`createdBy` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pipelineDeals_id` PRIMARY KEY(`id`)
);
