export type ProposalSectionType = "headline" | "verification" | "renewal";

export type ProposalSeedLine = {
  serviceName: string;
  currentRate: string;
  proposedRate: string;
  rate2027: string;
  rate2028: string;
  rate2029: string;
  rate2030: string;
  discountLabel: string;
  unitNote: string;
  laneLabel: string;
  sourceLabel: string;
  sourceTab: string;
};

export type ProposalSeedSection = {
  title: string;
  sectionType: ProposalSectionType;
  laneLabel: string;
  note: string;
  lines: ProposalSeedLine[];
};

export type ProposalSeed = {
  proposalName: string;
  clientName: string;
  slug: string;
  proposalTitle: string;
  proposalSubtitle: string;
  preparedBy: string;
  status: "draft" | "published";
  issueDate: string;
  effectiveDate: string;
  expirationDate: string;
  introText: string;
  verificationNote: string;
  brandingNote: string;
  publicSummary: string;
  logoMode: "wordmark" | "monogram";
  accentColor: string;
  accentSoftColor: string;
  sections: ProposalSeedSection[];
};

export const liquidDeathProposalSeed: ProposalSeed = {
  proposalName: "Liquid Death Renewal Proposal",
  clientName: "Liquid Death",
  slug: "liquid-death-renewal-2027-2030",
  proposalTitle: "Liquid Death Renewal Proposal",
  proposalSubtitle: "Presentation Layout and Rate Card",
  preparedBy: "L&M Logistics",
  status: "published",
  issueDate: "2026-04-13",
  effectiveDate: "2027-01-01",
  expirationDate: "2030-12-31",
  introText:
    "Prepared by L&M Logistics. Source verified against the shared Google Sheet tabs and the renewal model workbook. The presentation layer is intentionally polished for customer review while remaining tied to the internal pricing structure.",
  verificationNote:
    "All proposal-facing rates were cross-checked against the verified shared-sheet summary. Additional current-rate support lines were reviewed so the presentation captures the intended headline rows without overlooking source data.",
  brandingNote:
    "Use an elegant L&M Logistics presentation treatment. Keep the page clean and premium while avoiding weaker or placeholder logo treatments.",
  publicSummary:
    "Customer-facing renewal summary with verified current rates, approved proposal values, and renewal tiers for 2027 through 2030.",
  logoMode: "wordmark",
  accentColor: "#123f73",
  accentSoftColor: "#eaf1f8",
  sections: [
    {
      title: "Included Proposal Presentation Rates",
      sectionType: "headline",
      laneLabel: "Core proposal rows",
      note:
        "These are the proposal-facing lines shown in the branded presentation and mirrored on the public page.",
      lines: [
        {
          serviceName: "Handling In",
          currentRate: "11.44",
          proposedRate: "10.00",
          rate2027: "10.00",
          rate2028: "10.35",
          rate2029: "10.71",
          rate2030: "11.08",
          discountLabel: "12.6%",
          unitNote: "Per pallet",
          laneLabel: "PA / SC",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Handling Out",
          currentRate: "11.44",
          proposedRate: "10.00",
          rate2027: "10.00",
          rate2028: "10.35",
          rate2029: "10.71",
          rate2030: "11.08",
          discountLabel: "12.6%",
          unitNote: "Per pallet",
          laneLabel: "PA / SC",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Storage (SC)",
          currentRate: "13.52",
          proposedRate: "13.52",
          rate2027: "13.52",
          rate2028: "13.93",
          rate2029: "14.35",
          rate2030: "14.78",
          discountLabel: "0.0%",
          unitNote: "Per pallet",
          laneLabel: "SC",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Storage (PA/NJ)",
          currentRate: "13.00",
          proposedRate: "13.00",
          rate2027: "13.00",
          rate2028: "13.39",
          rate2029: "13.79",
          rate2030: "14.20",
          discountLabel: "0.0%",
          unitNote: "Per pallet",
          laneLabel: "PA / NJ",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Storage (16th to EOM)",
          currentRate: "9.36",
          proposedRate: "9.36",
          rate2027: "9.36",
          rate2028: "9.64",
          rate2029: "9.93",
          rate2030: "10.23",
          discountLabel: "0.0%",
          unitNote: "Per pallet",
          laneLabel: "PA / SC",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Labor",
          currentRate: "65.78",
          proposedRate: "52.00",
          rate2027: "52.00",
          rate2028: "53.56",
          rate2029: "55.17",
          rate2030: "56.82",
          discountLabel: "21.0%",
          unitNote: "Per hour",
          laneLabel: "Warehouse labor",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "IT Requests",
          currentRate: "182.00",
          proposedRate: "182.00",
          rate2027: "182.00",
          rate2028: "187.46",
          rate2029: "193.08",
          rate2030: "198.87",
          discountLabel: "0.0%",
          unitNote: "Per hour",
          laneLabel: "Admin services",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Order Processing (blended)",
          currentRate: "5.20",
          proposedRate: "8.00",
          rate2027: "8.00",
          rate2028: "8.24",
          rate2029: "8.49",
          rate2030: "8.74",
          discountLabel: "+53.8%",
          unitNote: "Per order",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Case Pick / Repalletize",
          currentRate: "0.42",
          proposedRate: "0.60",
          rate2027: "0.60",
          rate2028: "0.62",
          rate2029: "0.64",
          rate2030: "0.66",
          discountLabel: "+42.9%",
          unitNote: "Per case",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Destroy Product",
          currentRate: "0.18",
          proposedRate: "0.16",
          rate2027: "0.16",
          rate2028: "0.16",
          rate2029: "0.17",
          rate2030: "0.17",
          discountLabel: "11.1%",
          unitNote: "Per can",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Tray Labeling (4 Sides)",
          currentRate: "2.08",
          proposedRate: "2.08",
          rate2027: "2.08",
          rate2028: "2.14",
          rate2029: "2.20",
          rate2030: "2.27",
          discountLabel: "0.0%",
          unitNote: "Per case",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Pallet Strapping / Banding",
          currentRate: "3.75",
          proposedRate: "3.75",
          rate2027: "3.75",
          rate2028: "3.86",
          rate2029: "3.98",
          rate2030: "4.10",
          discountLabel: "0.0%",
          unitNote: "Per instance",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Pallet Supply Fee",
          currentRate: "13.57",
          proposedRate: "13.57",
          rate2027: "13.57",
          rate2028: "13.98",
          rate2029: "14.40",
          rate2030: "14.83",
          discountLabel: "0.0%",
          unitNote: "Per pallet",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Rush Fee",
          currentRate: "5.46",
          proposedRate: "5.46",
          rate2027: "5.46",
          rate2028: "5.62",
          rate2029: "5.79",
          rate2030: "5.97",
          discountLabel: "0.0%",
          unitNote: "27.30 minimum",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Heat Shrink",
          currentRate: "0.94",
          proposedRate: "0.94",
          rate2027: "0.94",
          rate2028: "0.97",
          rate2029: "1.00",
          rate2030: "1.03",
          discountLabel: "0.0%",
          unitNote: "Per case",
          laneLabel: "National addendum",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "First Pick",
          currentRate: "2.86",
          proposedRate: "",
          rate2027: "2.86",
          rate2028: "2.95",
          rate2029: "3.04",
          rate2030: "3.13",
          discountLabel: "—",
          unitNote: "Per pick",
          laneLabel: "Small parcel",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Additional Case Pick",
          currentRate: "1.04",
          proposedRate: "",
          rate2027: "1.04",
          rate2028: "1.07",
          rate2029: "1.10",
          rate2030: "1.14",
          discountLabel: "—",
          unitNote: "Per pick",
          laneLabel: "Small parcel",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
        {
          serviceName: "Box",
          currentRate: "Cost +",
          proposedRate: "",
          rate2027: "Cost +",
          rate2028: "Cost +",
          rate2029: "Cost +",
          rate2030: "Cost +",
          discountLabel: "—",
          unitNote: "Supply fee",
          laneLabel: "Small parcel",
          sourceLabel: "Verified current rates and approved presentation direction",
          sourceTab: "2025 Current / Sheet1",
        },
      ],
    },
    {
      title: "Additional Current-Rate Lines Verified from the Shared Link",
      sectionType: "verification",
      laneLabel: "Source review coverage",
      note:
        "These additional rows were reviewed as supporting current-rate coverage even though they are not all shown as headline proposal lines.",
      lines: [
        {
          serviceName: "Outside Carrier BOL",
          currentRate: "2.68",
          proposedRate: "",
          rate2027: "2.68",
          rate2028: "2.76",
          rate2029: "2.84",
          rate2030: "2.93",
          discountLabel: "Reviewed",
          unitNote: "Per order",
          laneLabel: "National addendum",
          sourceLabel: "Additional current-rate support",
          sourceTab: "2025 Current",
        },
        {
          serviceName: "Destroy Product - 24 Can Case",
          currentRate: "4.28",
          proposedRate: "",
          rate2027: "4.28",
          rate2028: "4.41",
          rate2029: "4.54",
          rate2030: "4.68",
          discountLabel: "Reviewed",
          unitNote: "Per case",
          laneLabel: "National addendum",
          sourceLabel: "Additional current-rate support",
          sourceTab: "2025 Current",
        },
        {
          serviceName: "Destroy Pallets",
          currentRate: "9.64",
          proposedRate: "",
          rate2027: "9.64",
          rate2028: "9.93",
          rate2029: "10.23",
          rate2030: "10.54",
          discountLabel: "Reviewed",
          unitNote: "Per pallet",
          laneLabel: "National addendum",
          sourceLabel: "Additional current-rate support",
          sourceTab: "2025 Current",
        },
        {
          serviceName: "Case Labeling",
          currentRate: "0.27",
          proposedRate: "",
          rate2027: "0.27",
          rate2028: "0.28",
          rate2029: "0.29",
          rate2030: "0.30",
          discountLabel: "Reviewed",
          unitNote: "Per label",
          laneLabel: "National addendum",
          sourceLabel: "Additional current-rate support",
          sourceTab: "2025 Current",
        },
        {
          serviceName: "Pallet Labeling",
          currentRate: "0.27",
          proposedRate: "",
          rate2027: "0.27",
          rate2028: "0.28",
          rate2029: "0.29",
          rate2030: "0.30",
          discountLabel: "Reviewed",
          unitNote: "Per label",
          laneLabel: "National addendum",
          sourceLabel: "Additional current-rate support",
          sourceTab: "2025 Current",
        },
      ],
    },
    {
      title: "Renewal Model by Service and Year",
      sectionType: "renewal",
      laneLabel: "2027 to 2030 tiers",
      note:
        "Internal command-page values can update these yearly tiers before republishing. The public page displays the approved schedule grouped by service type.",
      lines: [
        {
          serviceName: "Storage (weighted program rate)",
          currentRate: "13.26",
          proposedRate: "13.26",
          rate2027: "13.26",
          rate2028: "13.66",
          rate2029: "14.07",
          rate2030: "14.49",
          discountLabel: "Tiered",
          unitNote: "Per pallet-month",
          laneLabel: "Consolidated",
          sourceLabel: "Renewal model summary",
          sourceTab: "Consolidated / Summary",
        },
        {
          serviceName: "Handling (weighted program rate)",
          currentRate: "11.44",
          proposedRate: "10.00",
          rate2027: "10.00",
          rate2028: "10.35",
          rate2029: "10.71",
          rate2030: "11.08",
          discountLabel: "Tiered",
          unitNote: "Per pallet",
          laneLabel: "Consolidated",
          sourceLabel: "Renewal model summary",
          sourceTab: "Consolidated / Summary",
        },
        {
          serviceName: "Labor program rate",
          currentRate: "65.78",
          proposedRate: "52.00",
          rate2027: "52.00",
          rate2028: "53.56",
          rate2029: "55.17",
          rate2030: "56.82",
          discountLabel: "Tiered",
          unitNote: "Per hour",
          laneLabel: "Operations",
          sourceLabel: "Renewal model summary",
          sourceTab: "Inputs / Summary",
        },
      ],
    },
  ],
};
