CREATE TABLE `proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`publicId` varchar(40) NOT NULL,
	`proposalName` varchar(255) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`proposalTitle` varchar(255) NOT NULL,
	`proposalSubtitle` varchar(255) NOT NULL,
	`preparedBy` varchar(255) NOT NULL,
	`issueDate` varchar(20) NOT NULL,
	`effectiveDate` varchar(20) NOT NULL,
	`expirationDate` varchar(20) NOT NULL,
	`introText` text NOT NULL,
	`verificationNote` text NOT NULL,
	`brandingNote` text NOT NULL,
	`publicSummary` text NOT NULL,
	`serviceLanes` json NOT NULL,
	`sections` json NOT NULL,
	`logoMode` enum('wordmark','monogram') NOT NULL DEFAULT 'wordmark',
	`accentColor` varchar(24) NOT NULL,
	`accentSoftColor` varchar(24) NOT NULL,
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`publicSlug` varchar(255) NOT NULL,
	`createdByUserId` int,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `proposals_id` PRIMARY KEY(`id`),
	CONSTRAINT `proposals_publicId_unique` UNIQUE(`publicId`),
	CONSTRAINT `proposals_publicSlug_unique` UNIQUE(`publicSlug`)
);
